services: 
  app: 
    build: . 
    ports: 
    - "5173:3000" # Web app 
    - "8080:8080" # faucet 
    - "9001:9001" # shard proxy 
    - "13001:13001" # shard 
    volumes: 
    - ../..:/linera-protocol
    environment:
    - VITE_HMR_PORT=5173    